Repository UBC-MDS/encodeR, pull requests merged in 2020-03, with the labels that each got.

#40 created data folder and added testing data
  data/testing_data.csv
Labels: R, enhancement

#46 Add target_encoder.R code part and basic tests
  DESCRIPTION
  R/target_encoder.R
  man/target_encoder.Rd
  tests/testthat/test-target_encoder.R
Labels: R, enhancement, individual

#44 Add conjugate_encoder.R, change README, and add associated basic tests
  DESCRIPTION
  NAMESPACE
  R/cat_boost_encoder.R
  R/conjugate_encoder.R
  R/utils-pipe.R
  README.Rmd
  README.md
  man/cat_boost_encoder.Rd
  man/conjugate_encoder.Rd
  tests/test_onehot_encoder.R
  tests/testthat/test-conjugate_encoder.R
  tests/testthat/test-onehot_encoder.R
Labels: R, enhancement, individual

#43 Bronwyn frequency encoder and basic test implementation
  DESCRIPTION
  R/frequency_encoder.R
  man/frequency_encoder.Rd
  man/target_encoder.Rd
  tests/testthat/test-frequency_encoder.R
Labels: R, enhancement, individual

#47 Add documentation for target_encoder.Rd and pipe.Rd, also run tests.
  DESCRIPTION
  NAMESPACE
  man/pipe.Rd
  man/target_encoder.Rd
  tests/testthat/test-conjugate_encoder.R
  tests/testthat/test-frequency_encoder.R
Labels: R, documentation

#49 Complete the implementation of frequency_encoder.R and the respective tests for it
  R/frequency_encoder.R
  tests/testthat/test-frequency_encoder.R
Labels: R

#48 Standardize output between functions
  R/conjugate_encoder.R
  R/frequency_encoder.R
  R/target_encoder.R
  README.Rmd
  README.md
  tests/testdata/testing_data.csv
  tests/testthat/test-conjugate_encoder.R
  tests/testthat/test-frequency_encoder.R
  tests/testthat/test-target_encoder.R
Labels: R, documentation

#51 Fix examples to pass CRAN checks
  R/conjugate_encoder.R
  R/frequency_encoder.R
  R/onehot_encoder.R
  R/target_encoder.R
  man/conjugate_encoder.Rd
  man/frequency_encoder.Rd
  man/onehot_encoder.Rd
  man/target_encoder.Rd
Labels: R, bug

#59 Add more tests for Target Encoder to cover all branches
  R/target_encoder.R
  tests/testthat/test-target_encoder.R
Labels: R, bug, enhancement

#63 Fix bug in target_encoder example to pass check(), fix merge conflict
  .github/workflows/R-CMD-check.yaml
  .gitignore
  DESCRIPTION
  R/target_encoder.R
  man/onehot_encoder.Rd
  man/target_encoder.Rd
  vignettes/.gitignore
  vignettes/encodeR-vignette.Rmd
Labels: documentation

#65 Add comments, defensive error handling, and tests to frequency_encoder()
  R/frequency_encoder.R
  tests/testthat/test-frequency_encoder.R
Labels: R

#64 Remove caret dependency, rewrite ohe
  DESCRIPTION
  R/onehot_encoder.R
Labels: R, bug

#67 Added defensive code, comments, and tests for the onehot_encoder function
  R/onehot_encoder.R
  tests/testthat/test-frequency_encoder.R
  tests/testthat/test-onehot_encoder.R
Labels: R

#68 Finish vignette and add our website
  DESCRIPTION
  R/onehot_encoder.R
  docs/404.html
  docs/CONDUCT.html
  docs/CONTRIBUTING.html
  docs/CONTRIBUTORS.html
  docs/LICENSE-text.html
  docs/LICENSE.html
  docs/articles/encodeR-vignette.html
  docs/articles/index.html
  docs/authors.html
  docs/docsearch.css
  docs/docsearch.js
  docs/index.html
  docs/link.svg
  docs/pkgdown.css
  docs/pkgdown.js
  docs/pkgdown.yml
  docs/reference/conjugate_encoder.html
  docs/reference/figures/README-pressure-1.png
  docs/reference/frequency_encoder.html
  docs/reference/index.html
  docs/reference/onehot_encoder.html
  docs/reference/pipe.html
  docs/reference/target_encoder.html
  tests/testthat/test-onehot_encoder.R
  vignettes/encodeR-vignette.Rmd
Labels: R, documentation

#69 Fix site documentation, add pkgdown with usethis, fix typos
  .Rbuildignore
  R/conjugate_encoder.R
  README.Rmd
  README.md
  _pkgdown.yml
  docs/articles/encodeR-vignette.html
  docs/reference/conjugate_encoder.html
  man/conjugate_encoder.Rd
  vignettes/encodeR-vignette.Rmd
Labels: bug, documentation

#70 Add to readme, and fix authors
  DESCRIPTION
  README.Rmd
  README.md
  docs/404.html
  docs/CONDUCT.html
  docs/CONTRIBUTING.html
  docs/CONTRIBUTORS.html
  docs/LICENSE-text.html
  docs/LICENSE.html
  docs/articles/encodeR-vignette.html
  docs/articles/index.html
  docs/authors.html
  docs/index.html
  docs/reference/conjugate_encoder.html
  docs/reference/frequency_encoder.html
  docs/reference/index.html
  docs/reference/onehot_encoder.html
  docs/reference/pipe.html
  docs/reference/target_encoder.html
Labels: documentation

#73 Fix typos, documentation, long lines and other minor things
  DESCRIPTION
  R/conjugate_encoder.R
  R/frequency_encoder.R
  R/onehot_encoder.R
  R/target_encoder.R
  docs/404.html
  docs/CONDUCT.html
  docs/CONTRIBUTING.html
  docs/CONTRIBUTORS.html
  docs/LICENSE-text.html
  docs/LICENSE.html
  docs/articles/encodeR-vignette.html
  docs/articles/index.html
  docs/authors.html
  docs/index.html
  docs/reference/conjugate_encoder.html
  docs/reference/frequency_encoder.html
  docs/reference/index.html
  docs/reference/onehot_encoder.html
  docs/reference/pipe.html
  docs/reference/target_encoder.html
  man/conjugate_encoder.Rd
  man/frequency_encoder.Rd
  man/onehot_encoder.Rd
  man/target_encoder.Rd
  tests/testthat/test-conjugate_encoder.R
  tests/testthat/test-frequency_encoder.R
  tests/testthat/test-onehot_encoder.R
  vignettes/encodeR-vignette.Rmd
Labels: documentation
